### PR TITLE
`a` word, and also 🍷? 🤣

### PR DESCRIPTION
**Pull request by tallguyjenks**
❤️

### CODE REVIEW

**Comment by adiman9** [comment]
The wine part is actually correct - I work at a wine analytics company - maybe I change it to the emoji though!. Good spot on the other typo though.

**Comment by tallguyjenks** [comment]
HAHA fair enough!

**Review by tallguyjenks — COMMENTED** [review]
changed to 🍷️

**Comment by adiman9** [comment]
Perfect thank you :)

**Pull request merged**
